import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ProductProvider } from "@/ContextApi/AllProductsContext";
import { SingleProductProvider } from "@/ContextApi/SingleProductContex";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f1f5f9]`}
      >
        {/* ✅ Wrap both providers properly */}
        <ProductProvider>
          <SingleProductProvider>
            {children}
          </SingleProductProvider>
        </ProductProvider>
      </body>
    </html>
  );
};

export default RootLayout;
